INSERT INTO `mau_khaosat` (`id`, `ten_mau`, `mota`, `version`, `trangthai`, `nguoi_tao_id`, `created_at`, `updated_at`) VALUES
(1, 'Phiếu lấy ý kiến của Sinh viên/Sinh viên tốt nghiệp về tầm nhìn, sứ mạng/triết lý giáo dục.', 'Nhằm nâng cao chất lượng đào tạo nguồn nhân lực đáp ứng nhu cầu thị trường lao động, Nhà trường rất mong nhận được ý kiến của các em sinh viên/sinh viên tốt nghiệp về tầm nhìn, sứ mạng/triết lý giáo dục của Trường Đại học Sao Đỏ. Ý kiến của các em là cơ sở để Nhà trường rà soát, điều chỉnh, công bố công khai và phổ biến tới các bên liên quan. Thông tin trả lời sẽ được bảo mật theo quy định, vì vậy mong các em ghi đầy đủ thông tin và bày tỏ quan điểm thẳng thắn, khách quan. Nếu có thắc mắc hoặc trao đổi các em vui lòng liên hệ theo địa chỉ ở cuối bảng câu hỏi này.', 1, 'active', 1, '2025-10-06 13:47:01', '2025-10-06 14:37:18');

INSERT INTO `cauhoi_khaosat` (`id`, `mau_khaosat_id`, `noidung_cauhoi`, `loai_cauhoi`, `batbuoc`, `thutu`, `page`, `cau_dieukien_id`, `dieukien_hienthi`, `trangthai`, `created_at`, `updated_at`) VALUES
(1, 1, 'Sinh viên/Sinh viên tốt nghiệp được tham gia xây dựng và phát triển tầm nhìn, sứ mạng/triết lý giáo dục của Nhà trường', 'rating', 1, 1, 1, NULL, NULL, 1, '2025-10-06 14:37:57', '2025-10-06 14:38:46'),
(2, 1, 'Tầm nhìn, sứ mạng/triết lý giáo dục của Nhà trường đáp ứng được nhu cầu và sự hài lòng của người học', 'rating', 1, 2, 1, NULL, NULL, 1, '2025-10-06 14:38:13', '2025-10-06 14:38:52'),
(3, 1, 'Nội dung tầm nhìn, sứ mạng/triết lý giáo dục phù hợp với định hướng phát triển nhà trường và chiến lược phát triển kinh tế - xã hội', 'rating', 1, 3, 1, NULL, NULL, 1, '2025-10-06 14:38:32', '2025-10-06 14:38:58'),
(4, 1, 'Tầm nhìn, sứ mạng/triết lý giáo dục định kỳ được điều chỉnh, cải tiến trong quá trình phát triển Nhà trường', 'rating', 1, 4, 1, NULL, NULL, 1, '2025-10-06 14:39:12', '2025-10-06 14:39:12'),
(5, 1, 'Tầm nhìn, sứ mạng/triết lý giáo dục của Nhà trường được công bố chính thức và phổ biến rộng rãi', 'rating', 1, 5, 1, NULL, NULL, 1, '2025-10-06 14:39:22', '2025-10-06 14:39:22');
